[project]
name = "rslogger-video"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "opencv-python>=4.11.0",
    "websockets>=13.0",
    "numpy>=1.21.0",
]

